the-hacking-team/happy-minute

- Gemfile
- Gemfile.lock
- app/mailers/application_mailer.rb
- app/models/owner.rb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/layouts/devise.html.erb
- app/views/static_pages/home.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- config/routes.rb
- db/migrate/20200905093605_devise_create_owners.rb
- db/schema.rb
- test/fixtures/owners.yml
- test/models/owner_test.rb
First pull request for devise owner and the associated devise mailing
> installing devise for Owner and first parameters for devise's mailing

- Gemfile
- Gemfile.lock
- app/mailers/owner_mailer.rb
- app/models/owner.rb
- app/views/owner_mailer/welcome_email.html.erb
- config/application.rb
- config/environments/development.rb
- config/environments/production.rb
- test/mailers/owner_mailer_test.rb
- test/mailers/previews/owner_mailer_preview.rb
NOT using sendgrid nor mailjet, just SMTP :) 
Closes #6
> Mailer using IONOS SMTP (contact@happy-minute.com)

- db/migrate/20200907202645_create_businesses.rb
- db/migrate/20200907211107_create_items.rb
- db/migrate/20200907211621_create_happy_prices.rb
- db/migrate/20200907211848_create_happy_codes.rb
- db/migrate/20200909085033_add_first_and_last_name_to_owners.rb
- db/schema.rb
Adding first_name and last_name to Owners
Adding phone number and photo to Bussiness
Adding photo to Items
> Update database schema

- app/models/owner.rb
- db/schema.rb
- db/seeds.rb
> First seed

- app/assets/javascripts/businesses.coffee
- app/assets/stylesheets/businesses.scss
- app/controllers/businesses_controller.rb
- app/helpers/businesses_helper.rb
- app/views/businesses/create.html.erb
- app/views/businesses/destroy.html.erb
- app/views/businesses/edit.html.erb
- app/views/businesses/index.html.erb
- app/views/businesses/new.html.erb
- app/views/businesses/show.html.erb
- app/views/businesses/update.html.erb
- config/routes.rb
- test/controllers/business_controller_test.rb
First version for sharing all together
> Business controller index show edit update 

- app/assets/javascripts/items.coffee
- app/assets/stylesheets/application.css
- app/assets/stylesheets/happy_styles.css
- app/assets/stylesheets/items.scss
- app/controllers/items_controller.rb
- app/helpers/items_helper.rb
- app/views/items/edit.html.erb
- app/views/items/index.html.erb
- app/views/items/show.html.erb
- config/routes.rb
- test/controllers/items_controller_test.rb
CRUD, ugly front, no validates
> Items controller

- app/views/items/_form.html.erb
- app/views/items/_header.html.erb
- app/views/items/_item.html.erb
- app/views/items/edit.html.erb
- app/views/items/index.html.erb
- app/views/items/new.html.erb
- app/views/items/show.html.erb
- config/routes.rb
- db/seeds.rb
> Front for Item (show, new, edit, index)

- app/assets/javascripts/business_follows.coffee
- app/assets/stylesheets/business_follows.scss
- app/controllers/business_follows_controller.rb
- app/helpers/business_follows_helper.rb
- app/mailers/customer_mailer.rb
- app/models/business_follow.rb
- app/models/customer.rb
- app/models/owner.rb
- app/views/business_follows/create.html.erb
- app/views/businesses/index.html.erb
- app/views/businesses/show.html.erb
- app/views/customer_mailer/welcome_email.html.erb
- app/views/customers/show.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- db/migrate/20200910085824_add_first_and_last_name_to_customers.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/business_follows_controller_test.rb
- test/mailers/customer_mailer_test.rb
- test/mailers/previews/customer_mailer_preview.rb
- Adding the Customer Controller
- Fixing Signout NavBar
- Feature Follow - UnFollow
- Connection Mailer Customer
- Adding first name and last name to customer model
> Customers controller To Mailer

- Gemfile
- Gemfile.lock
- app/assets/javascripts/happy_codes.coffee
- app/assets/javascripts/happy_prices.coffee
- app/assets/stylesheets/happy_codes.scss
- app/assets/stylesheets/happy_prices.scss
- app/controllers/happy_codes_controller.rb
- app/controllers/happy_prices_controller.rb
- app/helpers/happy_codes_helper.rb
- app/helpers/happy_prices_helper.rb
- app/models/happy_price.rb
- app/models/item.rb
- app/views/happy_prices/_form.html.erb
- app/views/happy_prices/new.html.erb
- app/views/items/_item.html.erb
- app/views/items/show.html.erb
- config/application.rb
- config/routes.rb
- db/seeds.rb
- test/controllers/happy_codes_controller_test.rb
- test/controllers/happy_prices_controller_test.rb
Owner can create Happy Minute temporary prices
Happy Prices are shown in Item views
Update Seed
> Happy price initial

- README.md
PR to open the discussion on what should be in the README
=> Use "See rich diff" to see the README in modified files
> Very first version of README

- app/controllers/businesses_controller.rb
- app/controllers/items_controller.rb
- app/dashboards/business_dashboard.rb
- app/dashboards/item_dashboard.rb
- app/views/businesses/index.html.erb
- db/migrate/20200907202645_create_businesses.rb
- db/migrate/20200907211107_create_items.rb
- db/schema.rb
- db/seeds.rb
removed from business model
removed from item model
seed now adapted to this removal
controllers (businesses ans items) adapted
And dashbord admin adapted too
Remove photo from first view
> field photo as a string removed form database

- app/views/customers/show.html.erb
Profile page for customer was not working if customer was following businesses without custom pictures
> Fix picture in customer profile

- app/views/owners/show.html.erb
Implemented cards of the businesses in the view show
> Update owner show

- README.md
Add logo
Update domain names
@the-hacking-team/the-hacking-team feel free to complete this draft
> Update README for MVP

- app/assets/stylesheets/happy_colors.css
- app/assets/stylesheets/happy_styles.scss
- app/controllers/business_photos_controller.rb
- app/controllers/item_photos_controller.rb
- app/views/businesses/show.html.erb
- app/views/items/edit.html.erb
- app/views/items/show.html.erb
fix bugs mvp: rescue error photos, max-width business photos
> fix bugs mvp: rescue error photos, max-width business photos

- app/models/category.rb
- app/models/item.rb
- db/migrate/20200914121951_create_categories.rb
- db/migrate/20200914123504_remove_category_from_item.rb
- db/migrate/20200914123923_add_position_to_item.rb
- db/migrate/20200914134508_add_category_to_item.rb
- db/schema.rb
- db/seeds.rb
- test/fixtures/categories.yml
- test/models/category_test.rb
Removing column Category in Item Table
Adding column Position in Model Table
Edition of Seed
Correction of DB Relationships
> Adding Feature Item Category

- app/models/item.rb
- app/models/item_tag.rb
- app/models/tag.rb
- db/migrate/20200914145158_create_tags.rb
- db/migrate/20200914145322_create_item_tags.rb
- db/migrate/20200914150705_add_tag_to_item.rb
- db/schema.rb
- test/fixtures/item_tags.yml
- test/fixtures/tags.yml
- test/models/item_tag_test.rb
- test/models/tag_test.rb
- Adding Tag Table
- Adding TagItem JointTable
- Setting relationships between Tag & Item tables though Item Tag
> Feature adding item tag

- app/assets/stylesheets/happy_styles.scss
- app/views/shared/_navbar.html.erb
> Website marketing valorisation

- app/controllers/admin/categories_controller.rb
- app/controllers/admin/item_tags_controller.rb
- app/controllers/admin/tags_controller.rb
- app/dashboards/category_dashboard.rb
- app/dashboards/item_tag_dashboard.rb
- app/dashboards/tag_dashboard.rb
- config/routes.rb
Update of the admin board with the following pages:
- Tag
- ItemTag
- Category
> Add tag and category to admin board

- app/controllers/menu_items_controller.rb
- app/controllers/menus_controller.rb
- app/views/items/edit.html.erb
- app/views/items/index.html.erb
- app/views/menus/edit.html.erb
- app/views/menus/new.html.erb
- app/views/menus/show.html.erb
add menu feature front: synthetic menus appear in item index, edit menu displays menu items list, possibility to destroy menu_items, fix some bugged routes
> add menu feature front

- app/controllers/items_controller.rb
- app/views/items/_form.html.erb
Design of Category View Item#new
> Categories form edition

- app/controllers/items_controller.rb
- app/views/items/_category.html.erb
- app/views/items/index.html.erb
Updated the view of the menu:
- Items sorted by categories
- Tags displayed on items
> Display items by category

- app/views/businesses/show.html.erb
Light modification: added icons to business show
> Modify business show

- app/views/items/_category.html.erb
- app/views/items/_form.html.erb
- app/views/items/_item.html.erb
Small Commit adding cancel button
Adding Tags to Partial Views
> Navigation cancel addition

- app/controllers/items_controller.rb
add @categories to def edit in item controller
> Updated item controller's def edit to display dropdown select

- app/controllers/application_controller.rb
- app/models/customer.rb
- app/models/owner.rb
- app/views/devise/registrations/new.html.erb
- config/locales/devise.fr.yml
Forbidding registration of Owner and Customer without password confirmation
> Bug password confirmation devise

- app/assets/javascripts/item_tags.coffee
- app/assets/stylesheets/happy_colors.css
- app/assets/stylesheets/item_tags.scss
- app/controllers/item_tags_controller.rb
- app/controllers/items_controller.rb
- app/helpers/item_tags_helper.rb
- app/models/item_tag.rb
- app/views/items/edit.html.erb
- app/views/items/index.html.erb
- app/views/menus/edit.html.erb
- config/routes.rb
- test/controllers/item_tags_controller_test.rb
modifying item edit form to add tag selector
add fonctionnality edit allergens, create and destroy
button add a menu disappears if not owner
> Add form tags

- app/views/items/_item.html.erb
- app/views/items/show.html.erb
- app/views/shared/_alerts.html.erb
Slight corrections ;
- Deleting infinite Loop
- Confirmation Step before Item Deletion
- Colorizing Flash Alert for Login User
> Correction features roman

- app/models/happy_price.rb
> Fix validates

- app/assets/stylesheets/happy_colors.css
- app/controllers/businesses_controller.rb
- app/views/businesses/new.html.erb
- app/views/owners/show.html.erb
- app/views/shared/_footer.html.erb
- Design of Owner Profile
- Business#New View improvement
- Adding Cancellation and Back buttons
- Footer Link to THP WebSite
> Designing owner profile

- app/controllers/items_controller.rb
- app/controllers/menus_controller.rb
- app/models/business.rb
- app/models/menu.rb
- app/views/businesses/show.html.erb
- app/views/happy_prices/index.html.erb
various bug fixes, see commits
> Fix errors edit

- app/assets/stylesheets/happy_colors.css
- app/views/businesses/show.html.erb
- app/views/happy_prices/index.html.erb
- app/views/items/_category.html.erb
- app/views/items/_item.html.erb
Designing Timer in :
_Category
_Item
Business#show
HappyPrice#index
> Timer happy price edition

- app/controllers/application_controller.rb
For example, redirect to the happy minute where the customer wants to log in
> Redirect to previous page after sign_in

- app/models/happy_price.rb
- app/views/happy_prices/edit.html.erb
- app/views/items/_item.html.erb
start_date allowed in past for update to work
Add a delete button
> Happy price update UX (can delete, start_date can be past)
